refresh:
  fields:
    entry_id:
      selector:
        config_entry:
          integration: ffbb_tracker

get_next_matches:
  fields:
    entry_id:
      selector:
        config_entry:
          integration: ffbb_tracker
    limit:
      default: 3
      selector:
        number:
          min: 1
          max: 20
          mode: box

get_standings:
  fields:
    entry_id:
      selector:
        config_entry:
          integration: ffbb_tracker
