name: Validate

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # tous les jours, pour détecter les breaking changes HA/HACS
  workflow_dispatch:

permissions: {}

jobs:
  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master

  hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
